eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJtZWQtdXNlckB0ZXN0LmNvbSIsInJzSWQiOm51bGwsInVzZXJJZCI6MTE1NjU5NywiYXV0aG9yaXRpZXMiOlsiQU5BTFlUSUNfUlUiLCJPUEVSQVRPUiIsIkNPT1JESU5BVE9SIiwiRVhFQ1VUT1IiLCJDVVJBVE9SIiwiTUFOQUdFUiIsIkFOQUxZVElDIiwiQURNSU4iLCJDQUxMX0NFTlRFUl9PUEVSQVRPUiIsIlNVUEVSQURNSU5JU1RSQVRPUl9PRyIsIk9SR0FOSVpBVElPTl9BRE1JTiIsIk1PREVSQVRPUiJdLCJjbGllbnRfaWQiOiJzb3VyY2VNYXAxIiwic3VwZXJVc2VyIjpudWxsLCJwYXRyb255bWljIjoi0JDQtNC80LjQvdC40YHRgtGA0LDRgtC-0YDQvtCy0LjRhyIsInN5c3RlbSI6ZmFsc2UsInN1cm5hbWUiOiLQkNC00LzQuNC90LjRgdGC0YDQsNGC0L7RgNC-0LIiLCJzY29wZSI6WyJhbnkiXSwibmFtZSI6ItCQ0LTQvNC40L3QuNGB0YLRgNCw0YLQvtGAIiwiZXhwIjoxNjUyNzcyMTY1LCJqdGkiOiI1ZWUzNWJmYy03ZGMwLTQ0MGMtYmM0Yy02ODU5NmIyOGJiYTgiLCJlbWFpbCI6Im1lZC11c2VyQHRlc3QuY29tIn0.9K5WnwDNtuvoVnc5aAyou3QSUlLMQrrkTU2nVcgnCG4

POST http://localhost:5050/appeal-service/appeals/{id}/lock
